name: Gradle Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y update
        sudo apt-get -y install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: wrapper
    - name: Gradle Test
      run: |
        ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check
    - name: codecov.io
      uses: codecov/codecov-action@v4.3.1
