# This is a basic workflow to help you get started with Actions

name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Tag / Release Version (e.g. 1.0.10)'
        type: string
        required: true

env:
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Template
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create Tag
        run: |
          git tag -a ${{ env.RELEASE_VERSION }} -m "Add tag ${{ env.RELEASE_VERSION }}"
          git push origin --tags
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Execute Gradle build
        run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check assemble -PdownloaderVersion=${{ env.RELEASE_VERSION }}
      - name: Create Release
        run: |
          gh release create ${{ env.RELEASE_VERSION }} './build/distributions/interlok-artifact-downloader-boot-${{ env.RELEASE_VERSION }}.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
